version: "3.9"

services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      - POSTGRES_DB=anihub_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  web:
    build: .
    environment: 
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=die12833@gmail.com
      - DJANGO_SUPERUSER_PASSWORD=1234
      # - AES_SECRET_KEY=12345678901234567890123456789012 # La que pusiste en settings
    command:
      - /bin/bash
      - -c
      - |
        python manage.py makemigrations
        python manage.py migrate
        python manage.py createsuperuser --noinput || true
        python manage.py runserver 0.0.0.0:8000
    container_name: django
    volumes:
      - .:/anihub
    ports:
      - "8000:8000"
    depends_on:
      - db
